version: '2.1'

services:
  nginx:
    image: wouterds/bitcoinprice.dev:nginx
    container_name: dev.bitcoinprice--nginx
    restart: unless-stopped
    mem_limit: 8mb
    ports:
      - "80:80"

  node:
    image: wouterds/bitcoinprice.dev:node
    container_name: dev.bitcoinprice--node
    restart: unless-stopped
    mem_limit: 64mb

  redis:
    image: redis:6
    container_name: dev.bitcoinprice--redis
    restart: unless-stopped
    mem_limit: 8mb
    ports:
      - "6379:6379"
