version: '2.1'

services:
  nginx:
    image: wouterds/bitcoinlive.dev:nginx
    container_name: dev.bitcoinlive--nginx
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=reverse-proxy'
      - 'traefik.http.middlewares.devbitcoinlive.redirectscheme.scheme=https'
      - 'traefik.http.routers.devbitcoinlive-http.entrypoints=web'
      - 'traefik.http.routers.devbitcoinlive-http.rule=Host(`bitcoinlive.dev`)'
      - 'traefik.http.routers.devbitcoinlive-http.middlewares=devbitcoinlive'
      - 'traefik.http.routers.devbitcoinlive-https.entrypoints=websecure'
      - 'traefik.http.routers.devbitcoinlive-https.rule=Host(`bitcoinlive.dev`)'
      - 'traefik.http.routers.devbitcoinlive-https.tls.certresolver=myhttpchallenge'
    restart: unless-stopped
    mem_limit: 8mb
    networks:
      - reverse-proxy

  node:
    image: wouterds/bitcoinlive.dev:node
    container_name: dev.bitcoinlive--node
    restart: unless-stopped
    mem_limit: 32mb

networks:
  reverse-proxy:
    external: true
