version: '2.1'

services:
  nginx:
    image: wouterds/bitcoinprice.dev:nginx
    container_name: dev.bitcoinprice--nginx
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=reverse-proxy'
      - 'traefik.http.middlewares.devbitcoinprice.redirectscheme.scheme=https'
      - 'traefik.http.routers.devbitcoinprice-http.entrypoints=web'
      - 'traefik.http.routers.devbitcoinprice-http.rule=Host(`bitcoinprice.dev`,`api.bitcoinprice.dev`)'
      - 'traefik.http.routers.devbitcoinprice-http.middlewares=devbitcoinprice'
      - 'traefik.http.routers.devbitcoinprice-https.entrypoints=websecure'
      - 'traefik.http.routers.devbitcoinprice-https.rule=Host(`bitcoinprice.dev`,`api.bitcoinprice.dev`)'
      - 'traefik.http.routers.devbitcoinprice-https.tls.certresolver=myhttpchallenge'
    restart: unless-stopped
    mem_limit: 8mb
    networks:
      - default
      - reverse-proxy

  node:
    image: wouterds/bitcoinprice.dev:node
    container_name: dev.bitcoinprice--node
    restart: unless-stopped
    mem_limit: 32mb

networks:
  reverse-proxy:
    external: true
